version: "3.9"

services:

  rust:
    container_name: rust-menger
    build: ./rust-menger
    ports:
      - "8087:8087"

  java:
    container_name: java-menger
    build: ./java-menger
    working_dir: /app
    volumes:
      - ./java-menger:/app
    command: mvn compile exec:java -Dexec.mainClass="com.example.menger.Main"
    ports:
      - "8088:8088"

  go:
    container_name: go-menger
    build: ./go-menger
    working_dir: /app
    volumes:
      - ./go-menger:/app
    command: go run main.go
    ports:
      - "8089:8089"

  bash:
    container_name: bash-menger
    build: ./bash-menger
    working_dir: /app
    volumes:
      - ./bash-menger:/app
    command: bash menger.sh
    ports:
      - "8090:8090"

  dart:
    container_name: dart-menger
    build: ./dart-menger
    working_dir: /app
    volumes:
      - ./dart-menger:/app
    command: dart run bin/main.dart
    ports:
      - "8091:8091"

  node:
    container_name: javascript-menger
    build: ./javascript-menger
    working_dir: /app
    volumes:
      - ./javascript-menger:/app
    command: node src/index.js
    ports:
      - "8092:8092"

  python:
    container_name: python-menger
    build: ./python-menger
    working_dir: /app
    volumes:
      - ./python-menger:/app
    command: python main.py
    ports:
      - "8093:8093"

  php:
    container_name: php-menger
    build: ./php-menger
    working_dir: /app
    volumes:
      - ./php-menger:/app
    command: php src/index.php
    ports:
      - "8094:8094"

  csharp:
    container_name: csharp-menger
    build: ./csharp-menger
    working_dir: /app
    volumes:
      - ./csharp-menger:/app
    command: dotnet run
    ports:
      - "8095:8095"