version: "3.9"

services:

  node:
    container_name: javascript-menger
    build: ./javascript-menger
    working_dir: /app
    volumes:
      - ./javascript-menger:/app
      - ./log/javascript:/logs
    command: node src/index.js
    ports:
      - "8092:8092"